title: Tracker de Filas VACINASAMPA Covid-19

defaults:
  - scope:
      path: 'data'
    values:
        layout: 'null'

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - main.rb
  - LICENSE
  - .github/
